export const appShellKinds = [
  'public',
  'auth',
  'onboarding',
  'tenant',
  'admin',
] as const

export type AppShellKind = (typeof appShellKinds)[number]

export type VerticalSlice =
  | 'auth-onboarding'
  | 'customer-order-receipt'
  | 'production-handoff'
  | 'payment-cash'
  | 'organization-master-data'
  | 'dashboard-reports'
  | 'billing'
  | 'platform-public'

export interface AppRouteDefinition {
  id: string
  path: string
  title: string
  description: string
  shell: AppShellKind
  slice: VerticalSlice
}

export const appRouteRegistry = [
  {
    id: 'public.home',
    path: '/',
    title: 'Operasional laundry yang lebih tertata',
    description: 'Landing publik dan pintu masuk trial LaundryKita.',
    shell: 'public',
    slice: 'platform-public',
  },
  {
    id: 'public.features',
    path: '/features',
    title: 'Fitur LaundryKita',
    description: 'Ringkasan modul MVP sesuai scope produk.',
    shell: 'public',
    slice: 'platform-public',
  },
  {
    id: 'public.pricing',
    path: '/pricing',
    title: 'Paket LaundryKita',
    description: 'Perbandingan paket, harga, limit, dan trial.',
    shell: 'public',
    slice: 'billing',
  },
  {
    id: 'public.contact',
    path: '/contact',
    title: 'Hubungi LaundryKita',
    description: 'Kanal bantuan resmi untuk calon pelanggan.',
    shell: 'public',
    slice: 'platform-public',
  },
  {
    id: 'auth.login',
    path: '/login',
    title: 'Masuk ke LaundryKita',
    description: 'Membuat sesi pengguna dengan aman.',
    shell: 'auth',
    slice: 'auth-onboarding',
  },
  {
    id: 'auth.register',
    path: '/register',
    title: 'Buat akun Owner',
    description: 'Registrasi akun pemilik laundry.',
    shell: 'auth',
    slice: 'auth-onboarding',
  },
  {
    id: 'auth.verify-email',
    path: '/verify-email',
    title: 'Verifikasi email',
    description: 'Memvalidasi email sebelum onboarding.',
    shell: 'auth',
    slice: 'auth-onboarding',
  },
  {
    id: 'auth.forgot-password',
    path: '/forgot-password',
    title: 'Lupa password',
    description: 'Meminta tautan reset tanpa membocorkan akun.',
    shell: 'auth',
    slice: 'auth-onboarding',
  },
  {
    id: 'auth.reset-password',
    path: '/reset-password',
    title: 'Atur password baru',
    description: 'Mengganti password melalui token yang valid.',
    shell: 'auth',
    slice: 'auth-onboarding',
  },
  {
    id: 'auth.accept-invitation',
    path: '/accept-invitation',
    title: 'Terima undangan',
    description: 'Menerima membership tenant dan outlet.',
    shell: 'auth',
    slice: 'auth-onboarding',
  },
  {
    id: 'auth.select-tenant',
    path: '/select-tenant',
    title: 'Pilih usaha laundry',
    description: 'Memilih membership aktif setelah login.',
    shell: 'auth',
    slice: 'auth-onboarding',
  },
  {
    id: 'public.terms',
    path: '/terms',
    title: 'Syarat penggunaan',
    description: 'Dokumen syarat penggunaan yang berlaku.',
    shell: 'public',
    slice: 'platform-public',
  },
  {
    id: 'public.privacy',
    path: '/privacy',
    title: 'Kebijakan privasi',
    description: 'Dokumen privasi dan pengelolaan data.',
    shell: 'public',
    slice: 'platform-public',
  },
  {
    id: 'onboarding.business',
    path: '/onboarding/business',
    title: 'Identitas usaha',
    description: 'Langkah pertama konfigurasi tenant.',
    shell: 'onboarding',
    slice: 'auth-onboarding',
  },
  {
    id: 'onboarding.outlet',
    path: '/onboarding/outlet',
    title: 'Outlet pertama',
    description: 'Menyiapkan outlet operasional pertama.',
    shell: 'onboarding',
    slice: 'auth-onboarding',
  },
  {
    id: 'onboarding.services',
    path: '/onboarding/services',
    title: 'Layanan laundry',
    description: 'Menyiapkan layanan, unit, harga, dan durasi.',
    shell: 'onboarding',
    slice: 'auth-onboarding',
  },
  {
    id: 'onboarding.complete',
    path: '/onboarding/complete',
    title: 'Tinjau dan mulai trial',
    description: 'Finalisasi onboarding secara idempotent.',
    shell: 'onboarding',
    slice: 'auth-onboarding',
  },
  {
    id: 'tenant.dashboard',
    path: '/app/:tenantSlug/dashboard',
    title: 'Dashboard',
    description: 'Ringkasan operasional tenant dan outlet.',
    shell: 'tenant',
    slice: 'dashboard-reports',
  },
  {
    id: 'tenant.orders',
    path: '/app/:tenantSlug/orders',
    title: 'Pesanan',
    description: 'Daftar dan pencarian pesanan laundry.',
    shell: 'tenant',
    slice: 'customer-order-receipt',
  },
  {
    id: 'tenant.orders.new',
    path: '/app/:tenantSlug/orders/new',
    title: 'Buat pesanan',
    description: 'Transaksi order cepat dengan total yang deterministik.',
    shell: 'tenant',
    slice: 'customer-order-receipt',
  },
  {
    id: 'tenant.orders.detail',
    path: '/app/:tenantSlug/orders/:orderId',
    title: 'Detail pesanan',
    description: 'Sumber detail, status, pembayaran, dan histori order.',
    shell: 'tenant',
    slice: 'customer-order-receipt',
  },
  {
    id: 'tenant.orders.edit',
    path: '/app/:tenantSlug/orders/:orderId/edit',
    title: 'Edit pesanan',
    description: 'Perubahan atau koreksi order sesuai state legal.',
    shell: 'tenant',
    slice: 'customer-order-receipt',
  },
  {
    id: 'tenant.orders.receipt',
    path: '/app/:tenantSlug/orders/:orderId/receipt',
    title: 'Nota pesanan',
    description: 'Preview dan print nota thermal 58 atau 80 mm.',
    shell: 'tenant',
    slice: 'customer-order-receipt',
  },
  {
    id: 'tenant.production',
    path: '/app/:tenantSlug/production',
    title: 'Produksi',
    description: 'Antrean dan transisi proses laundry.',
    shell: 'tenant',
    slice: 'production-handoff',
  },
  {
    id: 'tenant.customers',
    path: '/app/:tenantSlug/customers',
    title: 'Pelanggan',
    description: 'Daftar dan pencarian pelanggan tenant.',
    shell: 'tenant',
    slice: 'customer-order-receipt',
  },
  {
    id: 'tenant.customers.detail',
    path: '/app/:tenantSlug/customers/:customerId',
    title: 'Detail pelanggan',
    description: 'Profil dan histori order sesuai outlet scope.',
    shell: 'tenant',
    slice: 'customer-order-receipt',
  },
  {
    id: 'tenant.payments',
    path: '/app/:tenantSlug/payments',
    title: 'Pembayaran',
    description: 'Ledger pembayaran dan daftar piutang.',
    shell: 'tenant',
    slice: 'payment-cash',
  },
  {
    id: 'tenant.cash-register',
    path: '/app/:tenantSlug/cash-register',
    title: 'Kas',
    description: 'Sesi kas, pergerakan, dan rekonsiliasi.',
    shell: 'tenant',
    slice: 'payment-cash',
  },
  {
    id: 'tenant.reports',
    path: '/app/:tenantSlug/reports',
    title: 'Laporan',
    description: 'Laporan operasional dan rekonsiliasi.',
    shell: 'tenant',
    slice: 'dashboard-reports',
  },
  {
    id: 'tenant.settings.business',
    path: '/app/:tenantSlug/settings/business',
    title: 'Pengaturan usaha',
    description: 'Identitas tenant dan konfigurasi dasar.',
    shell: 'tenant',
    slice: 'organization-master-data',
  },
  {
    id: 'tenant.settings.outlets',
    path: '/app/:tenantSlug/settings/outlets',
    title: 'Pengaturan outlet',
    description: 'Outlet, assignment, penggunaan, dan limit.',
    shell: 'tenant',
    slice: 'organization-master-data',
  },
  {
    id: 'tenant.settings.services',
    path: '/app/:tenantSlug/settings/services',
    title: 'Pengaturan layanan',
    description: 'Katalog layanan dan harga laundry.',
    shell: 'tenant',
    slice: 'organization-master-data',
  },
  {
    id: 'tenant.settings.staff',
    path: '/app/:tenantSlug/settings/staff',
    title: 'Pengaturan pegawai',
    description: 'Invitation, membership, role, dan assignment.',
    shell: 'tenant',
    slice: 'organization-master-data',
  },
  {
    id: 'tenant.settings.roles',
    path: '/app/:tenantSlug/settings/roles',
    title: 'Pengaturan akses',
    description: 'Preset role dan capability sensitif.',
    shell: 'tenant',
    slice: 'organization-master-data',
  },
  {
    id: 'tenant.settings.billing',
    path: '/app/:tenantSlug/settings/billing',
    title: 'Subscription dan billing',
    description: 'Paket, status subscription, usage, dan recovery.',
    shell: 'tenant',
    slice: 'billing',
  },
  {
    id: 'admin.dashboard',
    path: '/admin',
    title: 'Platform dashboard',
    description: 'Ringkasan kesehatan tenant dan subscription.',
    shell: 'admin',
    slice: 'platform-public',
  },
  {
    id: 'admin.tenants',
    path: '/admin/tenants',
    title: 'Tenant platform',
    description: 'Pencarian tenant tanpa data transaksi pelanggan.',
    shell: 'admin',
    slice: 'platform-public',
  },
  {
    id: 'admin.tenants.detail',
    path: '/admin/tenants/:tenantId',
    title: 'Detail tenant platform',
    description: 'Metadata, subscription, usage, dan support action.',
    shell: 'admin',
    slice: 'platform-public',
  },
  {
    id: 'admin.plans',
    path: '/admin/plans',
    title: 'Plan versions',
    description: 'Versi paket, entitlement, limit, dan status.',
    shell: 'admin',
    slice: 'billing',
  },
  {
    id: 'admin.subscriptions',
    path: '/admin/subscriptions',
    title: 'Subscription platform',
    description: 'Pemantauan subscription dan event provider.',
    shell: 'admin',
    slice: 'billing',
  },
  {
    id: 'admin.audit-logs',
    path: '/admin/audit-logs',
    title: 'Audit log platform',
    description: 'Jejak tindakan sensitif dan correlation ID.',
    shell: 'admin',
    slice: 'platform-public',
  },
] as const satisfies readonly AppRouteDefinition[]
